### ISSUE TITLE
Segmentation fault with mailparse_msg_create()

### ISSUE THREAD

**Issue by mathroc** [php/pecl-mail-mailparse#22]
test to reproduce in #23 

I don't know if this is the same issue as #21 . At least I can reproduce it even with a MIME-Version header

**Comment by mathroc** [comment]
I can also say that this crash only occurs starting at mailparse3.1.3

**Comment by mathroc** [comment]
closing this since the issue is fixed now (since 3.1.4)

I'll let [the merge request adding a test reproducing the issue](https://github.com/php/pecl-mail-mailparse/pull/23) open in case you want to merge it to avoid introducing the same issue again later. otherwise feel free to close it too

thank you

**Comment by remicollet** [comment]
Reopen as 3.1.4 still crash... maybe related to build option/compiler (using gh22.phpt)

```
(gdb) bt
#0  0x00007ffff769e03d in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00005555557db452 in _estrdup (s=0x0) at /usr/src/debug/php82-php-8.2.8~RC1-1.fc37.remi.x86_64/Zend/zend_alloc.c:2673
#2  0x00007ffff7fb9acb in php_mimepart_process_line (workpart=0x7ffff726d7c0) at /home/php/git/mailparse/php_mailparse_mime.c:615
#3  php_mimepart_parse (part=0x7ffff726c3c0, buf=<optimized out>, bufsize=<optimized out>) at /home/php/git/mailparse/php_mailparse_mime.c:743
#4  0x00007ffff7fb9b69 in zif_mailparse_msg_parse (execute_data=<optimized out>, return_value=0x7ffff72150d0) at /home/php/git/mailparse/mailparse.c:1081
#5  0x0000555555871f64 in ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php82-php-8.2.8~RC1-1.fc37.remi.x86_64/Zend/zend_vm_execute.h:1312
#6  execute_ex (ex=0x0) at /usr/src/debug/php82-php-8.2.8~RC1-1.fc37.remi.x86_64/Zend/zend_vm_execute.h:56044
#7  0x0000555555878235 in zend_execute (op_array=0x7ffff7296000, return_value=0x0) at /usr/src/debug/php82-php-8.2.8~RC1-1.fc37.remi.x86_64/Zend/zend_vm_execute.h:60408
#8  0x0000555555805470 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /usr/src/debug/php82-php-8.2.8~RC1-1.fc37.remi.x86_64/Zend/zend.c:1827
#9  0x000055555579ea0a in php_execute_script (primary_file=primary_file@entry=0x7fffffffc040) at /usr/src/debug/php82-php-8.2.8~RC1-1.fc37.remi.x86_64/main/main.c:2542
#10 0x00005555558eedcf in do_cli (argc=82, argv=0x555555e10bc0) at /usr/src/debug/php82-php-8.2.8~RC1-1.fc37.remi.x86_64/sapi/cli/php_cli.c:964
#11 0x000055555563f526 in main (argc=82, argv=0x555555e10bc0) at /usr/src/debug/php82-php-8.2.8~RC1-1.fc37.remi.x86_64/sapi/cli/php_cli.c:1333

```

**Comment by remicollet** [comment]
Please try 92dde0bd6d6658e111e6022ead36eb7d1177caa1

**Comment by mathroc** [comment]
Built the extension from this commit and all our related skipped tests are now green again, thank you!
